redid app structure, added styled components
KittySaur/music-app pull request #1
Opened 2022-08-18 19:46 UTC by KittySaur

2022-08-18 20:14 UTC, yadimko requested changes

2022-08-18 20:14 UTC, yadimko commented on src/components/bar_components/PlayerControls.js
> +          width={"22px"}
мб лучше вынести в отлельный файл - style

2022-08-18 20:14 UTC, yadimko commented on src/components/bar_components/PlayerTrack.js
> +        <a href="http://">{props.author}</a>
"#" в ссылке если она никуда не ведет

2022-08-18 20:14 UTC, yadimko commented on src/components/main_components/centerblock_components/FilterButtons.js
> +          onClick={() => setClickedId((prevId) => (prevId === id ? null : id))}
почитай про useCallback. тут ты мапишь массив и на каждый элемент создаешь новую функцию

2022-08-18 20:14 UTC, yadimko commented on src/components/main_components/centerblock_components/Playlist.js
> +    }, 5000);
таймаут надо удалить - почитай как

2022-08-18 20:14 UTC, yadimko commented on src/components/main_components/centerblock_components/Playlist.js
> +          <PlaylistItem key={id}>
наверное стоит вынести в отдельный компонент все полотно

2022-08-18 20:14 UTC, yadimko commented on src/components/main_components/sidebar_components/SidebarBlock.js
> +    setTimeout(() => {
надо удалять таймаут - почитать как

2022-08-20 22:07 UTC, KittySaur commented on src/components/bar_components/PlayerTrack.js
> +        <a href="http://">{props.author}</a>
Если я оставляю решётку, тогда eslint ругается и выдаёт ошибку

2022-08-22 18:02 UTC, yadimko approved these changes

2022-08-22 18:57 UTC, merged