Seventh hw
KittySaur/music-app pull request #4
Opened 2022-09-01 03:10 UTC by KittySaur

Добавила тему с использованием useContext и ThemeProvider

2022-09-01 06:36 UTC, mrerberg requested changes

2022-09-01 06:36 UTC, mrerberg commented on src/App.js
> +    <ThemeContext.Provider value={{ darkTheme, setDarkTheme }}>
Объект { darkTheme, setDarkTheme } рекомендую обернуть в хук useMemo, чтобы избежать лишних перерисовок

2022-09-01 06:36 UTC, mrerberg commented on src/App.js
>    const cookieValue = document.cookie.replace(
Почему replace? Ты же хочешь куку достать

2022-09-01 06:36 UTC, mrerberg commented on src/components/bar_components/PlayerControls.js
> +          <ControlSvg width="22px" height="20px" alt="play">
Почему alt=play?

2022-09-01 06:36 UTC, mrerberg commented on src/components/bar_components/PlayerControls.js
> +          // stroke={"#696969"}
Мертвый код удаляем

2022-09-01 06:36 UTC, mrerberg commented on src/components/main_components/Navigation.js
> +      <Logo src={darkTheme ? "img/logo.png" : "img/logo_modal.png"} />
Лучше вынеси этот тернарник в переменную

const logo = darkTheme ? "img/logo.png" : "img/logo_modal.png"

2022-09-01 06:36 UTC, mrerberg commented on src/components/main_components/nav_components/NavMenu.js
> +              <svg
У получился огромное тернарное выражение. Вынеси 2 эти svg как отдельные компоненты

2022-09-01 06:36 UTC, mrerberg commented on src/index.js
> +//import GlobalStyles from "./styles/GlobalStyles";
Мертвый код

2022-09-02 07:24 UTC, mrerberg requested changes

2022-09-02 07:24 UTC, mrerberg commented on src/App.js
> +  const cookieValue = document.cookie;
Зачем тебе тут куки сейчас?

2022-09-02 07:24 UTC, mrerberg commented on src/App.js
> +      value={useMemo(() => {
Вынеси в переменную результат выполнения useMemo

2022-09-02 07:24 UTC, mrerberg commented on src/components/bar_components/PlayerControls.js
> +          <ControlSvg width="22px" height="20px" alt="pause">
Иконки проще делать так

https://github.com/core-ds/icons/blob/master/packages/classic/src/AccountAddMBlackIcon.tsx

2022-09-07 06:26 UTC, mrerberg requested changes

2022-09-07 06:26 UTC, mrerberg commented on src/App.js
> +  const themeValue = useMemo(() => {
const themeValue = useMemo(() => ({ darkTheme, setDarkTheme }), [darkTheme, setDarkTheme]);

2022-09-07 06:26 UTC, mrerberg commented on src/components/Bar.js
> +      progress: (currentTime / duration) * 100,
Данное форматирование рекомендую вынести в отдельную функцию, которая будет принимать 2 аргумента: currentTime и duration

`(currentTime / duration) * 100`

2022-09-07 06:26 UTC, mrerberg commented on src/components/Bar.js
> +    let width = progressRef.current.clientWidth;
Почему let?

2022-09-07 06:26 UTC, mrerberg commented on src/components/bar_components/Bar.styled.js
> +  background-color: ${({ theme }) => theme.colors.svgBgC};
Что значит C в svgBgC?

2022-09-09 18:39 UTC, KittySaur commented on src/components/bar_components/Bar.styled.js
> +  background-color: ${({ theme }) => theme.colors.svgBgC};
Это для Color, я переименую понятней

2022-09-13 06:39 UTC, mrerberg requested changes

2022-09-13 06:39 UTC, mrerberg commented on src/assets/Dislike.js
> +const SvgDislike = (props) => (
DislikeIcon

Не привязывайся к тегу в названии (svg)

2022-09-13 06:39 UTC, mrerberg commented on src/skeletons/Skeletons.css
> +  background-color: #313131;
Переменные цветов рекомендовал бы вынести в js переменные, либо в css переменные

2022-09-19 06:58 UTC, mrerberg approved these changes

2022-09-19 17:20 UTC, closed without merging