Eight hw
KittySaur/music-app pull request #5
Opened 2022-09-20 19:38 UTC by KittySaur

1 из 5 заданий - логика авторизации

2022-09-21 06:45 UTC, mrerberg requested changes

2022-09-21 06:45 UTC, mrerberg commented on src/App.js
> +  // const user = false;
Мертвый код удаляем

2022-09-21 06:45 UTC, mrerberg commented on src/components/enter_components/LoginForm.js
> +      dispatch(setLogin({ ...userData }));
Почему экшен называется login, если в него кладется userData? setUser?

2022-09-21 06:45 UTC, mrerberg commented on src/components/enter_components/LoginForm.js
> +      setEmail("");
А зачем? Это не обязательно чистить

2022-09-21 06:45 UTC, mrerberg commented on src/components/enter_components/LoginForm.js
> +      setPassword("");
А зачем? Это не обязательно чистить

2022-09-21 06:45 UTC, mrerberg commented on src/components/enter_components/LoginForm.js
> +      <SignupButton onClick={handleSignUpButton}>
Почему бы не воспользоваться компонентом Link, чтобы не писать обработчик клика?

2022-09-21 06:45 UTC, mrerberg commented on src/components/enter_components/SignupForm.js
>  function LoginForm() {
Почему этот компонент называется LoginForm?

2022-09-21 06:45 UTC, mrerberg commented on src/components/enter_components/SignupForm.js
> +  const isValid = password === repeatPassword;
Вынеси функции валидации за компонент. Так проще будет и код тестировать и читать

2022-09-21 06:45 UTC, mrerberg commented on src/components/enter_components/SignupForm.js
> +      <ModalButton padding={"30px"} onClick={handleSubmit}>
Не надо хардкода стилей, используй классы

2022-09-21 06:45 UTC, mrerberg commented on src/components/main_components/nav_components/NavMenu.js
> +          <MenuLink to={"/login"} onClick={() => dispatch(logOut())}>
<MenuLink to="/login" onClick={() => dispatch(logOut())}>

2022-09-21 06:45 UTC, mrerberg commented on src/components/main_components/nav_components/NavMenu.js
>          <li key={3}>
Зачем тут key?

2022-09-21 06:45 UTC, mrerberg commented on src/features/api/apiSlice.js
> +//     "id": 7,
Мертвый код

2022-09-21 06:45 UTC, mrerberg commented on src/features/auth/authSlice.js
> +  initialState: { user: null, token: null, id: null },
Лучше вынести initialState как отдельный объект, чтобы попроще читалось

2022-09-21 06:45 UTC, mrerberg commented on src/pages/ProtectedRoute.js
> +  return token !== null && token.access ? (
Давай без тернарников постараемся обойтись в разметке.

```
if(token !== null && token.access) return <Outlet />

return <Navigate to="/login" state={{ from: location }} replace />
```

2022-09-21 06:45 UTC, mrerberg commented on src/pages/ProtectedRoute.js
> +  return token !== null && token.access ? (
А еще лучше

```
if(token === null && !token.access) return <Navigate to="/login" state={{ from: location }} replace />

return  <Outlet />
```

2022-09-25 00:21 UTC, KittySaur commented on src/components/enter_components/LoginForm.js
> +      <SignupButton onClick={handleSignUpButton}>
Если использовать Link, тогда сразу перенаправление происходит до отправки запроса и в итоге ошибка, я уже так пробовала

2022-09-25 00:27 UTC, KittySaur commented on src/components/main_components/nav_components/NavMenu.js
>          <li key={3}>
Потому что без ключа консоль ругается

2022-12-20 16:40 UTC, merged